import * as THREE from 'three';

export class EnemyProjectileSystem {
  constructor(scene,bus,camera,map){this.scene=scene;this.bus=bus;this.camera=camera;this.map=map;this.active=[];this.pool=[];this.lasers=new Map();this.warnings=[];bus.on('enemy:projectile',e=>this.spawn(e));bus.on('enemy:sniperCharge',e=>this.startLaser(e));bus.on('enemy:sniperInterrupted',({enemy})=>this.removeLaser(enemy));bus.on('enemy:killed',({enemy})=>this.removeLaser(enemy));}
  make(){const mesh=new THREE.Mesh(new THREE.SphereGeometry(.11,8,6),new THREE.MeshStandardMaterial({color:0xff6042,emissive:0xff351c,emissiveIntensity:2}));mesh.visible=false;this.scene.add(mesh);return mesh;}
  spawn(e){const mesh=this.pool.pop()||this.make(),origin=e.enemy.group.position.clone().add(new THREE.Vector3(0,1.25,0)),target=this.camera.position.clone().add(new THREE.Vector3((Math.random()-.5)*.45,0,(Math.random()-.5)*.45)),dir=target.sub(origin).normalize();mesh.position.copy(origin);mesh.scale.setScalar(e.type==='grenade'?2.1:1);mesh.visible=true;const p={...e,mesh,velocity:dir.multiplyScalar(e.speed),life:e.type==='grenade'?5:3};this.active.push(p);if(e.type==='grenade'){const duration=Math.max(.6,origin.distanceTo(this.camera.position)/e.speed),ring=new THREE.Mesh(new THREE.RingGeometry(2.5,3,40),new THREE.MeshBasicMaterial({color:0xff314f,transparent:true,opacity:.65,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(this.camera.position).setY(.04);this.scene.add(ring);this.warnings.push({ring,life:duration,max:duration});this.bus.emit('enemy:grenadeWarning',{position:ring.position,radius:3,duration});}}
  startLaser({enemy}){this.removeLaser(enemy);const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-1)]),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xff174f,transparent:true,opacity:.75}));this.scene.add(line);this.lasers.set(enemy,line);}
  removeLaser(enemy){const line=this.lasers.get(enemy);if(line){this.scene.remove(line);line.geometry.dispose();line.material.dispose();this.lasers.delete(enemy);}}
  update(dt,active=true){if(!active)return;for(let i=this.warnings.length-1;i>=0;i--){const w=this.warnings[i];w.life-=dt;w.ring.material.opacity=.25+.4*Math.abs(Math.sin(w.life*8));if(w.life<=0){this.scene.remove(w.ring);w.ring.geometry.dispose();w.ring.material.dispose();this.warnings.splice(i,1);}}for(const [enemy,line] of this.lasers){if(!enemy.alive){this.removeLaser(enemy);continue;}line.geometry.setFromPoints([enemy.group.position.clone().add(new THREE.Vector3(0,1.45,0)),this.camera.position.clone()]);}
    for(let i=this.active.length-1;i>=0;i--){const p=this.active[i];p.life-=dt;p.mesh.position.addScaledVector(p.velocity,dt);const playerDist=p.mesh.position.distanceTo(this.camera.position),worldHit=this.map.collides(p.mesh.position,p.type==='grenade'?.2:.08);if(playerDist<(p.type==='grenade'?2.8:.65)||worldHit||p.life<=0){if(playerDist<(p.type==='grenade'?3.2:.7))this.bus.emit('enemy:attack',{enemy:p.enemy,damage:p.damage});this.bus.emit('enemy:projectileImpact',{position:p.mesh.position.clone(),type:p.type});p.mesh.visible=false;this.pool.push(p.mesh);this.active.splice(i,1);}}
  }
  clear(){this.active.forEach(p=>{p.mesh.visible=false;this.pool.push(p.mesh);});this.active=[];this.warnings.forEach(w=>{this.scene.remove(w.ring);w.ring.geometry.dispose();w.ring.material.dispose();});this.warnings=[];for(const enemy of [...this.lasers.keys()])this.removeLaser(enemy);}
}
