import { applyPose, defaultAnims } from '../weapons/animations.js';

export class Weapon {
  constructor(camera,bus,stats,data){this.camera=camera;this.bus=bus;this.stats=stats;this.data=data;this.anims=data.anims||defaultAnims();this.ammo=data.magazine;this.reserve=data.reserve;const model=data.makeModel();this.group=model.group;this.muzzle=model.muzzle;this.muzzleLight=model.muzzleLight;camera.add(this.group);this.restPosition=this.group.position.clone();this.restRotation=this.group.rotation.clone();this.restScale=this.group.scale.clone();this.rest={pos:this.restPosition,rot:this.restRotation,scale:this.restScale};this.cooldown=0;this.reloading=0;this.reloadDuration=0;this.reloadStage=0;this.fireTime=99;this.triggered=false;this.empoweredRounds=0;this.nextElement='ice';this.switchAnimation=null;this.switchLocked=false;this.lastYaw=camera.rotation.y;}
  hook(name,context={}){return this.data.effects?.[name]?.({weapon:this,...context});}
  // Camera yaw is sampled here so mouse and touch look share the same angular-rate source.
  update(dt,fire){this.cooldown-=dt;this.fireTime+=dt;const yaw=this.camera.rotation.y,yawDelta=Math.atan2(Math.sin(yaw-this.lastYaw),Math.cos(yaw-this.lastYaw)),yawRate=dt>0?yawDelta/dt:0;this.lastYaw=yaw;if(this.switchAnimation){this.updateSwitch(dt);if(!fire)this.triggered=false;return;}let reloadPose=null;if(this.reloading>0){this.reloading-=dt;const progress=1-this.reloading/this.reloadDuration;reloadPose=this.anims.reload({active:true,progress});const stage=Math.min(3,Math.floor(progress*3)+1);if(stage!==this.reloadStage){this.reloadStage=stage;this.bus.emit('weapon:reloadStage',{stage:['','remove','insert','chamber'][stage],weapon:this});}if(this.reloading<=0)this.finishReload();}const returnTime=.11+this.data.recoil*.7;applyPose(this.group,this.rest,[this.anims.recoil({fireTime:this.fireTime,returnTime,recoil:this.data.recoil}),reloadPose,this.anims.idle({now:performance.now()}),this.anims.moveSway({owner:this,yawRate,dt})]);if(!fire)this.triggered=false;}
  tryShoot(){if(this.switchLocked||this.switchAnimation||this.reloading>0||this.cooldown>0)return false;if(this.ammo<=0){this.reload();return false;}this.triggered=true;this.fireTime=0;this.ammo--;const categoryRate=this.data.category==='auto'?this.stats.get('autoFireRate'):1;this.cooldown=1/(this.data.fireRate*this.stats.get('fireRate')*categoryRate);this.hook('onShoot');this.bus.emit('weapon:shoot',{weapon:this,data:this.data});if(Math.random()<this.stats.get('doubleShotChance'))this.bus.emit('weapon:shoot',{weapon:this,data:this.data,echo:true});return true;}
  reload(){if(this.switchLocked||this.switchAnimation||this.reloading>0||this.ammo>=this.capacity()||this.reserve<=0)return false;if(this.memoryReady){this.finishReload();this.bus.emit('weapon:reload',{duration:0});return true;}this.reloading=this.reloadDuration=this.data.reload/this.stats.get('reloadSpeed');this.reloadStage=0;this.bus.emit('weapon:reload',{duration:this.reloading});return true;}
  finishReload(){const need=this.capacity()-this.ammo,take=Math.min(need,this.reserve);this.ammo+=take;if(Number.isFinite(this.reserve))this.reserve-=take;this.hook('onReload');this.bus.emit('weapon:reloaded');}
  capacity(){const heavy=this.data.rarity==='legendary'?this.stats.get('heavyAmmo'):1;return Math.round(this.data.magazine*this.stats.get('magazine')*heavy);}
  beginSwitch(direction,onComplete){this.group.visible=true;this.switchLocked=true;this.switchAnimation={direction,elapsed:0,duration:.25,onComplete};applyPose(this.group,this.rest,[this.anims.switch({animation:this.switchAnimation})]);}
  updateSwitch(dt){const animation=this.switchAnimation;if(!animation)return;animation.elapsed=Math.min(animation.duration,animation.elapsed+dt);applyPose(this.group,this.rest,[this.anims.switch({animation})]);if(animation.elapsed/animation.duration>=1){this.switchAnimation=null;this.switchLocked=false;animation.onComplete?.(this);}}
  dispose(){this.group.traverse(o=>{if(o.isMesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.map?.dispose();m.dispose();});}});this.camera.remove(this.group);}
}
