// Weapon 只负责弹药、节奏与第一人称动画；造型和专属逻辑全部来自注册表定义。
export class Weapon {
  constructor(camera,bus,stats,data){this.camera=camera;this.bus=bus;this.stats=stats;this.data=data;this.ammo=data.magazine;this.reserve=data.reserve;const model=data.makeModel();this.group=model.group;this.muzzle=model.muzzle;this.muzzleLight=model.muzzleLight;camera.add(this.group);this.restPosition=this.group.position.clone();this.restRotation=this.group.rotation.clone();this.restScale=this.group.scale.clone();this.cooldown=0;this.reloading=0;this.reloadDuration=0;this.reloadStage=0;this.fireTime=99;this.triggered=false;this.empoweredRounds=0;this.nextElement='ice';this.switchAnimation=null;this.switchLocked=false;}
  hook(name,context={}){return this.data.effects?.[name]?.({weapon:this,...context});}
  update(dt,fire){this.cooldown-=dt;this.fireTime+=dt;const p=this.group.position,r=this.group.rotation,kick=this.data.recoil*.48,returnTime=.11+this.data.recoil*.7;p.copy(this.restPosition);r.copy(this.restRotation);this.group.scale.copy(this.restScale);if(this.switchAnimation){this.updateSwitch(dt);if(!fire)this.triggered=false;return;}if(this.fireTime<returnTime){const t=this.fireTime/returnTime,k=t<.18?t/.18:Math.exp(-(t-.18)*4.8)*Math.cos((t-.18)*Math.PI*2.2);p.z+=kick*k;r.x+=this.data.recoil*k;}if(this.reloading>0){this.reloading-=dt;const t=1-this.reloading/this.reloadDuration,s=Math.sin(Math.PI*t);p.y-=.075*s;r.z-=.42*s;const stage=Math.min(3,Math.floor(t*3)+1);if(stage!==this.reloadStage){this.reloadStage=stage;this.bus.emit('weapon:reloadStage',{stage:['','remove','insert','chamber'][stage],weapon:this});}if(this.reloading<=0)this.finishReload();}p.y+=Math.sin(performance.now()*.008)*.004;if(!fire)this.triggered=false;}
  tryShoot(){if(this.switchLocked||this.switchAnimation||this.reloading>0||this.cooldown>0)return false;if(this.ammo<=0){this.reload();return false;}this.triggered=true;this.fireTime=0;this.ammo--;const categoryRate=this.data.category==='auto'?this.stats.get('autoFireRate'):1;this.cooldown=1/(this.data.fireRate*this.stats.get('fireRate')*categoryRate);this.hook('onShoot');this.bus.emit('weapon:shoot',{weapon:this,data:this.data});if(Math.random()<this.stats.get('doubleShotChance'))this.bus.emit('weapon:shoot',{weapon:this,data:this.data,echo:true});return true;}
  reload(){if(this.switchLocked||this.switchAnimation||this.reloading>0||this.ammo>=this.capacity()||this.reserve<=0)return false;if(this.memoryReady){this.finishReload();this.bus.emit('weapon:reload',{duration:0});return true;}this.reloading=this.reloadDuration=this.data.reload/this.stats.get('reloadSpeed');this.reloadStage=0;this.bus.emit('weapon:reload',{duration:this.reloading});return true;}
  finishReload(){const need=this.capacity()-this.ammo,take=Math.min(need,this.reserve);this.ammo+=take;if(Number.isFinite(this.reserve))this.reserve-=take;this.hook('onReload');this.bus.emit('weapon:reloaded');}
  capacity(){const heavy=this.data.rarity==='legendary'?this.stats.get('heavyAmmo'):1;return Math.round(this.data.magazine*this.stats.get('magazine')*heavy);}
  // CS2 风格交错切换：旧枪下沉，新枪从下方抬起；曲线数据也供 headless 验证。
  beginSwitch(direction,onComplete){this.group.visible=true;this.switchLocked=true;this.switchAnimation={direction,elapsed:0,duration:.25,onComplete};if(direction==='in'){this.group.position.set(this.restPosition.x+.06,this.restPosition.y-.18,this.restPosition.z);this.group.rotation.x=this.restRotation.x+20*Math.PI/180;this.group.scale.copy(this.restScale).multiplyScalar(.85);}}
  updateSwitch(dt){const a=this.switchAnimation;if(!a)return; a.elapsed=Math.min(a.duration,a.elapsed+dt);const t=a.elapsed/a.duration,e=1-Math.pow(1-t,3);const p=this.group.position,r=this.group.rotation,s=this.group.scale;if(a.direction==='out'){p.x=this.restPosition.x+.08*e;p.y=this.restPosition.y-.15*e;r.x=this.restRotation.x-25*Math.PI/180*e;s.copy(this.restScale).multiplyScalar(1-.15*e);}else{p.x=this.restPosition.x+.06*(1-e);p.y=this.restPosition.y-.18*(1-e);r.x=this.restRotation.x+20*Math.PI/180*(1-e);s.copy(this.restScale).multiplyScalar(.85+.15*e);}if(t>=1){if(a.direction==='in'){p.copy(this.restPosition);r.copy(this.restRotation);s.copy(this.restScale);}this.switchAnimation=null;this.switchLocked=false;a.onComplete?.(this);}}
  dispose(){this.group.traverse(o=>{if(o.isMesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{m.map?.dispose();m.dispose();});}});this.camera.remove(this.group);}
}
