import * as THREE from 'three';import {Pool} from '../utils/Pool.js';
export class ParticleSystem{
  constructor(scene,bus,quality='medium'){this.scene=scene;this.max=quality==='low'?35:quality==='high'?100:65;this.pool=new Pool(()=>this.make(),this.max);bus.on('fx:burst',e=>this.burst(e.position,e.color,e.count));bus.on('fx:radial',e=>this.radial(e.position,e.radius,e.color,e.count));bus.on('fx:trail',e=>this.trail(e.position,e.color));bus.on('enemy:killed',({enemy})=>this.burst(enemy.group.position.clone().addScalar(.5),0x25d9ff,18));}
  make(){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.045,0),new THREE.MeshBasicMaterial());m.visible=false;this.scene.add(m);return{m,v:new THREE.Vector3(),life:0};}
  burst(pos,color,count){for(let i=0;i<Math.min(count,this.max);i++){const p=this.pool.acquire();if(!p)break;p.m.visible=true;p.m.position.copy(pos);p.m.material.color.set(color);p.v.set((Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5);p.life=.25+Math.random()*.35;}}
  radial(pos,radius,color,count=36){this.burst(pos,color,Math.min(14,count));const ringCount=Math.min(count,this.max);for(let i=0;i<ringCount;i++){const p=this.pool.acquire();if(!p)break;const angle=i/ringCount*Math.PI*2,dir=new THREE.Vector3(Math.cos(angle),.08+Math.random()*.18,Math.sin(angle));p.m.visible=true;p.m.position.copy(pos).addScaledVector(dir,radius*.92);p.m.material.color.set(color);p.m.scale.setScalar(.7+radius*.08);p.v.copy(dir).multiplyScalar(1.8+radius*.35);p.life=.45+Math.min(.45,radius*.055);}}
  trail(pos,color){const p=this.pool.acquire();if(!p)return;p.m.visible=true;p.m.position.copy(pos);p.m.material.color.set(color);p.m.scale.setScalar(.55);p.v.set(0,.25,0);p.life=.16;}
  update(dt){for(const p of this.pool.active){p.life-=dt;p.v.y-=9*dt;p.m.position.addScaledVector(p.v,dt);p.m.scale.setScalar(Math.max(.1,p.life*2));if(p.life<=0){p.m.visible=false;this.pool.release(p);}}}
}
