import * as THREE from 'three';

export class PlayerProjectileSystem{
  constructor(scene,bus,camera,map,enemies){this.scene=scene;this.bus=bus;this.camera=camera;this.enemies=enemies;this.active=[];this.pool=[];this.ray=new THREE.Raycaster();this.setMap(map);bus.on('weapon:projectile',e=>this.spawn(e));}
  setMap(map){this.map=map;this.world=[];map.group.updateMatrixWorld(true);map.group.traverse(o=>{if(o.isMesh)this.world.push(o);});}
  make(){const group=new THREE.Group(),body=new THREE.Mesh(new THREE.CylinderGeometry(.055,.075,.42,8),new THREE.MeshStandardMaterial({color:0xe9edf2,emissive:0xff7b2f,emissiveIntensity:1.5,metalness:.55})),glow=new THREE.PointLight(0xff6a20,4,3);body.rotation.x=Math.PI/2;group.add(body,glow);group.visible=false;this.scene.add(group);return group;}
  spawn({weapon,data}){const mesh=this.pool.pop()||this.make(),origin=weapon.muzzle.getWorldPosition(new THREE.Vector3()),direction=new THREE.Vector3(0,0,-1).applyQuaternion(this.camera.quaternion).normalize(),kind=data.projectileType||'rocket',speed=data.projectileSpeed||(kind==='grenade'?16:28);mesh.position.copy(origin);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),direction);mesh.scale.setScalar(kind==='grenade'?.8:1);mesh.visible=true;this.active.push({mesh,data,weapon,kind,velocity:direction.multiplyScalar(speed),life:6,trail:0});this.bus.emit('player:projectileSpawn',{position:origin.clone(),kind,data});}
  impact(projectile,position,enemy=null){this.bus.emit('player:projectileImpact',{position:position.clone(),enemy,data:projectile.data,weapon:projectile.weapon,kind:projectile.kind});projectile.mesh.visible=false;this.pool.push(projectile.mesh);this.active.splice(this.active.indexOf(projectile),1);}
  update(dt,active=true){if(!active)return;for(const p of [...this.active]){p.life-=dt;const previous=p.mesh.position.clone();if(p.kind==='grenade')p.velocity.y-=11.5*dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,-1),p.velocity.clone().normalize());p.trail-=dt;if(p.trail<=0){p.trail=.035;this.bus.emit('fx:trail',{position:p.mesh.position.clone(),color:p.kind==='grenade'?0xffc14a:0xff6828});}const travel=p.mesh.position.clone().sub(previous),distance=travel.length();this.ray.set(previous,travel.normalize());this.ray.far=distance+.08;const hit=this.ray.intersectObjects([...this.enemies.rayTargets(),...this.world],false)[0],enemy=hit?.object?.userData?.enemy;if(hit||p.life<=0)this.impact(p,hit?.point||p.mesh.position,enemy||null);}}
  clear(){for(const p of [...this.active]){p.mesh.visible=false;this.pool.push(p.mesh);}this.active=[];}
}
