import * as THREE from 'three';
export class ShootingSystem {
  constructor(camera,weapon,enemies,map,bus,stats){this.camera=camera;this.weapon=weapon;this.enemies=enemies;this.map=map;this.bus=bus;this.stats=stats;this.ray=new THREE.Raycaster();this.spread=0;this.world=[];this.fusionQueue=[];this.setMap(map);this.tracers=[];this.tracerCursor=0;this.makeTracerPool(40);bus.on('weapon:shoot',e=>this.fire(e.data,e.weapon||this.weapon));}
  setMap(map){this.map=map;this.world=[];map.group.traverse(o=>{if(o.isMesh)this.world.push(o);});}
  makeTracerPool(size){for(let i=0;i<size;i++){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(6),3));const material=new THREE.LineBasicMaterial({color:0xffd28c,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const line=new THREE.Line(geometry,material);line.visible=false;line.frustumCulled=false;this.map.scene.add(line);this.tracers.push({line,life:0,maxLife:.08});}}
  spawnTracer(start,end,color=0xffd28c){const t=this.tracers[this.tracerCursor++%this.tracers.length],a=t.line.geometry.attributes.position.array;a.set([start.x,start.y,start.z,end.x,end.y,end.z]);t.line.geometry.attributes.position.needsUpdate=true;t.life=t.maxLife=.06+Math.random()*.03;t.line.material.color.setHex(color);t.line.material.opacity=1;t.line.visible=true;}
  fire(data,weapon){
    const muzzle=weapon.muzzle.getWorldPosition(new THREE.Vector3());this.muzzleFx(weapon,muzzle);
    if(data.archetype==='launcher')this.bus.emit('weapon:projectile',{weapon,data});
    else if(data.archetype==='fusion'){const bolts=Math.max(1,data.pellets||5);for(let i=0;i<bolts;i++)this.fusionQueue.push({delay:i*.038,data,weapon});}
    else this.hitscan(data,weapon,data.pellets+Math.round(this.stats.get('pellets'))+(data.archetype==='shotgun'?Math.round(this.stats.get('shotgunPellets')):0));
    if(weapon.empoweredRounds>0)weapon.empoweredRounds--;
  }
  muzzleFx(weapon,position){weapon.muzzleLight.intensity=18;setTimeout(()=>weapon.muzzleLight&&(weapon.muzzleLight.intensity=0),42);this.bus.emit('fx:burst',{position,color:0xffc25b,count:11});setTimeout(()=>this.bus.emit('fx:burst',{position,color:0xb8d8e8,count:5}),25);}
  hitscan(data,weapon,pellets=1){
    this.spread=Math.min(.085,this.spread+data.spread*(data.archetype==='fusion'?.35:1.7));const muzzle=weapon.muzzle.getWorldPosition(new THREE.Vector3());
    for(let i=0;i<pellets;i++){
      const dir=new THREE.Vector3((Math.random()-.5)*this.spread,(Math.random()-.5)*this.spread,-1).normalize().applyQuaternion(this.camera.quaternion);this.ray.set(this.camera.getWorldPosition(new THREE.Vector3()),dir);this.ray.far=data.range||100;
      const hits=this.ray.intersectObjects([...this.enemies.rayTargets(),...this.world],false),end=hits.length?hits[0].point.clone():muzzle.clone().addScaledVector(dir,45+Math.random()*15);this.spawnTracer(muzzle,end,data.archetype==='fusion'?0xb987ff:0xffd28c);if(!hits.length)continue;
      const maxEnemies=1+Math.round(this.stats.get('penetration')),seen=new Set();for(const hit of hits){const enemy=hit.object.userData.enemy;if(!enemy?.alive){if(!seen.size){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);this.bus.emit('world:hit',{point:hit.point,normal});}break;}if(seen.has(enemy))continue;seen.add(enemy);const headshot=hit.object.name==='head',precision=['handcannon','sidearm'].includes(data.archetype);let damage=data.damage*this.stats.get('damage')*(precision?this.stats.get('pistolDamage'):1)*(headshot?(data.headshotMultiplier||2.35)*this.stats.get('headshotDamage'):1);if(enemy.health/enemy.maxHealth<.3)damage*=this.stats.get('executeDamage');if(weapon.empoweredRounds>0)damage*=1.5*this.stats.get('heavyDamage');if(Math.random()<this.stats.get('critChance'))damage*=this.stats.get('critDamage');damage=weapon.hook('onHit',{enemy,damage,headshot,point:hit.point,game:this.game})??Math.round(damage);const killed=enemy.health-damage<=0,applied=enemy.hit(Math.round(damage),headshot,this.camera.position,true);if(data.explosionRadius&&data.archetype!=='launcher')this.game?.radialDamage(hit.point,data.explosionRadius,damage*.55,enemy,0xff8a32);if(killed)weapon.hook('onKill',{enemy,game:this.game,headshot});this.bus.emit('shot:hit',{enemy,point:hit.point,damage:Math.round(applied),headshot});if(seen.size>=maxEnemies)break;}
    }
  }
  update(dt){for(const bolt of [...this.fusionQueue]){bolt.delay-=dt;if(bolt.delay<=0){this.hitscan(bolt.data,bolt.weapon,1);this.fusionQueue.splice(this.fusionQueue.indexOf(bolt),1);}}this.spread=Math.max(0,this.spread-dt*.065);for(const t of this.tracers){if(t.life<=0)continue;t.life-=dt;t.line.material.opacity=Math.max(0,t.life/t.maxLife);if(t.life<=0)t.line.visible=false;}this.bus.emit('crosshair:spread',{value:this.spread});}
}
