import * as THREE from 'three';
export class ShootingSystem {
  constructor(camera,weapon,enemies,map,bus,stats){this.camera=camera;this.weapon=weapon;this.enemies=enemies;this.map=map;this.bus=bus;this.stats=stats;this.ray=new THREE.Raycaster();this.spread=0;this.world=[];this.setMap(map);this.tracers=[];this.tracerCursor=0;this.makeTracerPool(40);bus.on('weapon:shoot',e=>this.fire(e.data));}
  setMap(map){this.map=map;this.world=[];map.group.traverse(o=>{if(o.isMesh)this.world.push(o);});}
  // 固定对象池复用曳光节点，连续开火不产生额外场景对象。
  makeTracerPool(size){for(let i=0;i<size;i++){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(6),3));const material=new THREE.LineBasicMaterial({color:0xffd28c,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const line=new THREE.Line(geometry,material);line.visible=false;line.frustumCulled=false;this.map.scene.add(line);this.tracers.push({line,life:0,maxLife:.08});}}
  spawnTracer(start,end){const t=this.tracers[this.tracerCursor++%this.tracers.length],a=t.line.geometry.attributes.position.array;a.set([start.x,start.y,start.z,end.x,end.y,end.z]);t.line.geometry.attributes.position.needsUpdate=true;t.life=t.maxLife=.06+Math.random()*.03;t.line.material.opacity=1;t.line.visible=true;}
  fire(data){
    const pellets=data.pellets+Math.round(this.stats.get('pellets'))+(data.category==='shotgun'?Math.round(this.stats.get('shotgunPellets')):0);this.spread=Math.min(.085,this.spread+data.spread*1.7);const mp=this.weapon.muzzle.getWorldPosition(new THREE.Vector3());
    for(let i=0;i<pellets;i++){
      const dir=new THREE.Vector3((Math.random()-.5)*this.spread,(Math.random()-.5)*this.spread,-1).normalize().applyQuaternion(this.camera.quaternion);this.ray.set(this.camera.getWorldPosition(new THREE.Vector3()),dir);this.ray.far=100;
      const hits=this.ray.intersectObjects([...this.enemies.rayTargets(),...this.world],false),end=hits.length?hits[0].point.clone():mp.clone().addScaledVector(dir,45+Math.random()*15);this.spawnTracer(mp,end);if(!hits.length)continue;
      const maxEnemies=1+Math.round(this.stats.get('penetration')),seen=new Set();for(const hit of hits){const enemy=hit.object.userData.enemy;if(!enemy?.alive){if(!seen.size){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);this.bus.emit('world:hit',{point:hit.point,normal});}break;}if(seen.has(enemy))continue;seen.add(enemy);const headshot=hit.object.name==='head';let damage=data.damage*this.stats.get('damage')*(data.category==='pistol'?this.stats.get('pistolDamage'):1)*(headshot?(data.headshotMultiplier||2.35)*this.stats.get('headshotDamage'):1);if(enemy.health/enemy.maxHealth<.3)damage*=this.stats.get('executeDamage');if(this.weapon.empoweredRounds>0)damage*=1.5*this.stats.get('heavyDamage');if(Math.random()<this.stats.get('critChance'))damage*=this.stats.get('critDamage');damage=this.weapon.hook('onHit',{enemy,damage,headshot,point:hit.point})??Math.round(damage);const killed=enemy.health-damage<=0;const applied=enemy.hit(Math.round(damage),headshot,this.camera.position,true);if(killed)this.weapon.hook('onKill',{enemy,game:this.game});this.bus.emit('shot:hit',{enemy,point:hit.point,damage:Math.round(applied),headshot});if(seen.size>=maxEnemies)break;}
    }
    if(this.weapon.empoweredRounds>0)this.weapon.empoweredRounds--;this.weapon.muzzleLight.intensity=18;setTimeout(()=>this.weapon.muzzleLight&&(this.weapon.muzzleLight.intensity=0),42);this.bus.emit('fx:burst',{position:mp,color:0xffc25b,count:11});setTimeout(()=>this.bus.emit('fx:burst',{position:mp,color:0xb8d8e8,count:5}),25);
  }
  update(dt){this.spread=Math.max(0,this.spread-dt*.065);for(const t of this.tracers){if(t.life<=0)continue;t.life-=dt;t.line.material.opacity=Math.max(0,t.life/t.maxLife);if(t.life<=0)t.line.visible=false;}this.bus.emit('crosshair:spread',{value:this.spread});}
}
