import fs from 'node:fs';import {spawn} from 'node:child_process';import {chromium} from 'playwright';
const out=new URL('../artifacts/feature-verify/',import.meta.url);fs.mkdirSync(out,{recursive:true});const port=41731,server=spawn('npm',['run','dev','--','--host','127.0.0.1','--port',String(port),'--strictPort'],{stdio:['ignore','pipe','pipe'],detached:true});
const ready=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Vite 启动超时')),15000),done=d=>{if(String(d).includes('Local:')){clearTimeout(timer);resolve();}};server.stdout.on('data',done);server.stderr.on('data',done);});
try{await ready;const browser=await chromium.launch({headless:true});
  // PC 俯视图分别加载两张地图，对比整体拓扑。
  for(const map of ['base','transportShip']){const page=await browser.newPage({viewport:{width:1280,height:720}});await page.goto(`http://127.0.0.1:${port}?verify=1&map=${map}`);await page.locator('#start').click();await page.evaluate(()=>{const g=window.__verifyGame;g.state='paused';g.weapon.group.visible=false;g.engine.camera.position.set(0,135,12);g.engine.camera.rotation.set(-Math.PI/2,0,0);g.engine.camera.fov=74;g.engine.camera.updateProjectionMatrix();});await page.waitForTimeout(300);await page.screenshot({path:new URL(`map-${map}-1280x720.png`,out).pathname});await page.close();}
  // 手机横屏实机布局：雷达带红点，并逐把展示三把金枪。
  const ctx=await browser.newContext({viewport:{width:812,height:375},screen:{width:812,height:375},isMobile:true,hasTouch:true,deviceScaleFactor:1});const page=await ctx.newPage();await page.goto(`http://127.0.0.1:${port}?verify=1&map=transportShip`);await page.locator('#start').click();await page.waitForTimeout(500);await page.evaluate(()=>{const g=window.__verifyGame;while(g.enemies.active.length<3)g.enemies.spawn(g.enemies.active.length===2?'elite':'basic',1);g.state='paused';g.engine.camera.position.set(0,1.72,52);g.engine.camera.rotation.set(0,0,0);g.player.yaw=0;g.enemies.active.forEach((e,i)=>e.group.position.set([-8,12,4][i],0,[35,29,20][i]));});for(const id of ['ace','khvostov','conditional']){await page.evaluate(id=>window.__verifyGame.switchWeapon(id),id);await page.waitForTimeout(180);await page.screenshot({path:new URL(`${id}-812x375.png`,out).pathname});}
  const result=await page.evaluate(()=>{const g=window.__verifyGame,W=g.weapon.constructor,defs={};
    const fakeStats={get(){return 1;}},fakeBus={emit(){}};let blast=null;g.switchWeapon('ace');g.weapon.ammo=1;const victim={group:{position:{}}};g.weapon.hook('onKill',{enemy:victim,game:{radialDamage(...a){blast=a;}}});g.weapon.reload();defs.ace={blastRadius:blast[1],blastDamage:blast[2],ammo:g.weapon.ammo,empowered:g.weapon.empoweredRounds};
    g.switchWeapon('khvostov');const target={};defs.khvostov=[0,1,2,3,4].map(()=>g.weapon.hook('onHit',{enemy:target,damage:22}));
    g.switchWeapon('conditional');const elements=[],enemy={applyElement(v){elements.push(v);}};g.weapon.hook('onShoot');g.weapon.hook('onHit',{enemy});g.weapon.hook('onShoot');g.weapon.hook('onHit',{enemy});defs.conditional={elements,slow:'40% / 1.5s',burn:'8/s / 2s'};
    const d=g.maps.transportShip,b=g.maps.base;defs.collision={shipWall:d.collides({x:-21,y:1.72,z:5},.38),shipLane:!d.collides({x:0,y:1.72,z:45},.38),baseWall:b.collides({x:60,y:1.72,z:0},.38)};defs.radarEnemies=g.enemies.active.filter(e=>e.alive).length;return defs;});
  fs.writeFileSync(new URL('logic-results.json',out),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
}finally{try{process.kill(-server.pid,'SIGTERM');}catch{}}
