import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawn,execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
import {BUFF_POOL,BATCH2_BUFF_IDS} from '../src/roguelike/buffPool.js';
import {Stats} from '../src/player/Stats.js';
import {BuffSystem} from '../src/roguelike/BuffSystem.js';
import {EventBus} from '../src/core/EventBus.js';

const out=new URL('../artifacts/batch2/',import.meta.url),weaponOut=new URL('weapons/',out);fs.mkdirSync(weaponOut,{recursive:true});
// 词条池配置与新增稀有度分布。
assert(BUFF_POOL.length>=50,'词条池不足 50');
const batch2=BUFF_POOL.filter(b=>BATCH2_BUFF_IDS.includes(b.id)),rarities={};for(const b of batch2)(rarities[b.rarity]??=[]).push(b);
assert.deepEqual(Object.fromEntries(Object.entries(rarities).map(([k,v])=>[k,v.length])),{common:8,rare:7,epic:4,legendary:1});
assert(BUFF_POOL.every(b=>b.id&&b.name&&b.desc&&['common','rare','epic','legendary'].includes(b.rarity)&&typeof b.apply==='function'),'词条配置不完整');
const bus=new EventBus(),stats=new Stats(),health={armor:0,heal(){},value:100},buffs=new BuffSystem(bus,stats,health);
const sampled=['pistolExpert','autoMaster','shotgunMaster','adrenaline','bounce','weakPoint','execution','piercing','lucky','overdrive'];
const before=Object.fromEntries(['pistolDamage','autoFireRate','shotgunPellets','lowHealthSpeed','jumpHeight','headshotDamage','executeDamage','penetration','coinGain','damage'].map(k=>[k,stats.get(k)]));
sampled.forEach(id=>buffs.apply(BUFF_POOL.find(b=>b.id===id)));
const effects=Object.fromEntries(Object.keys(before).map(k=>[k,{before:before[k],after:stats.get(k)}]));
assert(Object.values(effects).every(e=>e.after>e.before),'随机 10 词条没有全部改变属性');

const port=41742,server=spawn('npm',['run','dev','--','--host','127.0.0.1','--port',String(port),'--strictPort'],{stdio:['ignore','pipe','pipe']});
const ready=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Vite 启动超时')),15000);const done=d=>{if(String(d).includes('Local:')){clearTimeout(timer);resolve();}};server.stdout.on('data',done);server.stderr.on('data',done);});
const report={buffs:{poolSize:BUFF_POOL.length,batch2Distribution:Object.fromEntries(Object.entries(rarities).map(([k,v])=>[k,v.length])),sampled,effects},map:{},weapons:{}};
try{
 await ready;const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:720}});await page.goto(`http://127.0.0.1:${port}?verify=1`);
 await page.locator('#start').click();const cards=await page.locator('.mapOption b').allTextContents();assert.deepEqual(cards,['未来基地','运输船']);await page.locator('[data-map="transportShip"]').click();await page.locator('#confirmLoadout').click();await page.waitForTimeout(400);
 const flowStart=await page.evaluate(()=>{const g=window.__verifyGame;g.enemies.clear();g.input.state.move.y=1;return{position:g.engine.camera.position.toArray(),ammo:g.weapon.ammo,weapon:g.weapon.data.id};});await page.waitForTimeout(220);await page.evaluate(()=>{const g=window.__verifyGame;g.input.state.move.y=0;g.input.state.jump=true;g.input.state.fire=true;});await page.waitForTimeout(140);await page.evaluate(()=>{const g=window.__verifyGame;g.input.state.fire=false;g.cycleWeapon(1);});await page.waitForTimeout(320);const flowEnd=await page.evaluate(()=>{const g=window.__verifyGame;return{position:g.engine.camera.position.toArray(),ammo:g.inventory.find(w=>w.data.id==='smg').ammo,weapon:g.weapon.data.id};});assert(Math.hypot(flowEnd.position[0]-flowStart.position[0],flowEnd.position[2]-flowStart.position[2])>.3,'移动失败');assert(flowEnd.position[1]>1.72,'跳跃失败');assert(flowEnd.ammo<flowStart.ammo,'开枪失败');assert.notEqual(flowEnd.weapon,flowStart.weapon,'切枪失败');report.flow={start:flowStart,end:flowEnd,moved:true,jumped:true,fired:true,switched:true};
 const mapData=await page.evaluate(()=>{const g=window.__verifyGame,m=g.map;const spawnOpen=!m.collides(m.playerSpawn,.38);let collisionHits=0;for(let i=0;i<200;i++){const b=m.colliders[i%m.colliders.length],p={x:(b.min.x+b.max.x)/2,y:1.72,z:(b.min.z+b.max.z)/2};if(m.collides(p,.2))collisionHits++;}const before=g.map;dispatchEvent(new KeyboardEvent('keydown',{code:'KeyM'}));const switched=g.map!==before;dispatchEvent(new KeyboardEvent('keydown',{code:'KeyM'}));return{name:m.group.name,width:m.boundsX*2,length:m.boundsZ*2,spawnOpen,safeSpawns:m.safeSpawns.length,collisionHits,samples:200,selected:g.map===before,mSwitch:switched,boxTop:m.heightAt({x:13.2,y:7,z:17},.3)};});
 assert(Math.abs(mapData.width-42)<1&&Math.abs(mapData.length-96)<1);assert(mapData.spawnOpen&&mapData.collisionHits===200&&mapData.mSwitch&&mapData.selected);assert(mapData.boxTop>=2.6,'箱顶不可站立');report.map=mapData;
 await page.evaluate(()=>{const g=window.__verifyGame;g.state='paused';g.inventory.forEach(w=>w.group.visible=false);g.engine.camera.position.set(0,125,0);g.engine.camera.rotation.set(-Math.PI/2,0,0);g.engine.camera.fov=62;g.engine.camera.updateProjectionMatrix();});await page.waitForTimeout(150);await page.screenshot({path:new URL('transport-ship-top.png',out).pathname,animations:'disabled',timeout:8000});
 await page.evaluate(()=>{const g=window.__verifyGame;g.engine.camera.position.set(0,1.72,40);g.engine.camera.rotation.set(0,0,0);g.engine.camera.fov=74;g.engine.camera.updateProjectionMatrix();});await page.waitForTimeout(150);await page.screenshot({path:new URL('transport-ship-player.png',out).pathname,animations:'disabled',timeout:8000});
 const mobileContext=await browser.newContext({viewport:{width:812,height:375},screen:{width:812,height:375},isMobile:true,hasTouch:true,deviceScaleFactor:1});await mobileContext.addInitScript(()=>{const native=window.matchMedia.bind(window);window.matchMedia=q=>q.includes('pointer:coarse')?{matches:true,media:q,addEventListener(){},removeEventListener(){}}:native(q);});const mobile=await mobileContext.newPage();await mobile.goto(`http://127.0.0.1:${port}?verify=1`);await mobile.locator('#start').click();await mobile.locator('[data-map="transportShip"]').click();await mobile.locator('#confirmLoadout').click();await mobile.waitForTimeout(250);const cdp=await mobileContext.newCDPSession(mobile),snap=async path=>{const image=await cdp.send('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path,Buffer.from(image.data,'base64'));};
 const ids=['pistol','smg','shotgun','ace','khvostov','conditional'];for(const id of ids){await mobile.evaluate(id=>{const g=window.__verifyGame;const slots={pistol:['pistol','smg','shotgun'],smg:['pistol','smg','shotgun'],shotgun:['pistol','smg','shotgun'],ace:['ace','smg','shotgun'],khvostov:['pistol','khvostov','shotgun'],conditional:['pistol','smg','conditional']}[id];g.start({mapId:'transportShip',weaponIds:slots});g.state='paused';g.switchWeapon(id,true);},id);await mobile.waitForTimeout(120);const baseline=new URL(`weapons/${id}-baseline.png`,out).pathname,shot=new URL(`weapons/${id}-812x375.png`,out).pathname;await mobile.evaluate(()=>window.__verifyGame.weapon.group.visible=false);await snap(baseline);const data=await mobile.evaluate(()=>{const g=window.__verifyGame,w=g.weapon;w.group.visible=true;g.engine.camera.updateMatrixWorld(true);const pts=[];w.group.traverse(o=>{if(!o.isMesh)return;const p=o.getWorldPosition(o.position.clone()).project(g.engine.camera);pts.push({x:(p.x+1)*406,y:(1-p.y)*187.5});});const rect={left:Math.min(...pts.map(p=>p.x))-35,right:Math.max(...pts.map(p=>p.x))+35,top:Math.min(...pts.map(p=>p.y))-25,bottom:Math.max(...pts.map(p=>p.y))+25};let overlap=0,area=Math.max(1,(rect.right-rect.left)*(rect.bottom-rect.top));document.querySelectorAll('#actionControls button').forEach(b=>{const r=b.getBoundingClientRect(),x=Math.max(0,Math.min(rect.right,r.right)-Math.max(rect.left,r.left)),y=Math.max(0,Math.min(rect.bottom,r.bottom)-Math.max(rect.top,r.top));overlap+=x*y;});return{parts:w.group.userData.partCount,projection:rect,overlapRatio:overlap/area};});await snap(shot);assert(data.parts>=12,`${id} 部件不足`);assert(data.overlapRatio<.15,`${id} 与按钮重叠过多`);report.weapons[id]=data;}
 await browser.close();
}finally{server.kill('SIGTERM');}
// 用 PIL 对每把枪与隐藏枪模的同场景基线做像素差分。
const pil=execFileSync('python3',['-c',`from PIL import Image,ImageChops\nimport json,glob,os\nr={}\nfor p in glob.glob('${weaponOut.pathname}/*-812x375.png'):\n i=os.path.basename(p).split('-812')[0];a=Image.open(p).convert('RGB');b=Image.open('${weaponOut.pathname}/'+i+'-baseline.png').convert('RGB');d=ImageChops.difference(a,b);r[i]={'changedPixels':sum(1 for x in d.getdata() if x!=(0,0,0)),'bbox':d.getbbox()}\nprint(json.dumps(r))`],{encoding:'utf8'});report.pixelDiff=JSON.parse(pil);assert(Object.values(report.pixelDiff).every(d=>d.changedPixels>500),'枪模 PIL 差分不可见');
fs.writeFileSync(new URL('verification.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
process.exit(0);
