import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';
import {chromium} from 'playwright';
import * as THREE from 'three';
import {Weapon} from '../src/player/Weapon.js';
import {WEAPONS} from '../src/weapons/weaponData.js';
import {EventBus} from '../src/core/EventBus.js';
import {PlayerController} from '../src/player/PlayerController.js';
import {ScreenShake} from '../src/systems/ScreenShake.js';

const width=812,height=375,ids=Object.keys(WEAPONS),buttonIds=['fire','reload','switchWeapon','jump','menuBtn'];
const css=fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');
const out=new URL('../artifacts/step2-view/',import.meta.url);fs.mkdirSync(out,{recursive:true});
const report={generatedAt:new Date().toISOString(),assertions:{},weapons:{},screenshots:[]};
function cssNumber(id,name){const rule=css.match(new RegExp(`#${id}\\s*\\{([^}]*)\\}`))?.[1],v=rule?.match(new RegExp(`${name}\\s*:\\s*([\\d.]+)px`))?.[1];if(v===undefined)throw new Error(`无法读取 #${id} ${name}`);return Number(v);}
function buttonRect(id){const w=cssNumber(id,'width'),h=cssNumber(id,'height'),rule=css.match(new RegExp(`#${id}\\s*\\{([^}]*)\\}`))?.[1]||'';const left=rule.includes('right:')?width-cssNumber(id,'right')-w:cssNumber(id,'left'),top=rule.includes('bottom:')?height-cssNumber(id,'bottom')-h:cssNumber(id,'top');return{left,top,right:left+w,bottom:top+h};}
function overlap(a,b){const w=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left)),h=Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));return w*h/Math.max(1,(a.right-a.left)*(a.bottom-a.top));}
function projection(data){
  const camera=new THREE.PerspectiveCamera(75,width/height,.08,220),weapon=new Weapon(camera,{emit(){}},{get(){return 1;}},data);camera.updateMatrixWorld(true);const points=[];
  weapon.group.traverse(o=>{if(!o.isMesh)return;o.geometry.computeBoundingBox();const b=o.geometry.boundingBox;for(const x of[b.min.x,b.max.x])for(const y of[b.min.y,b.max.y])for(const z of[b.min.z,b.max.z]){const p=new THREE.Vector3(x,y,z).applyMatrix4(o.matrixWorld).project(camera);if(Math.abs(p.x)<=1&&Math.abs(p.y)<=1&&Math.abs(p.z)<=1)points.push({x:(p.x*.5+.5)*width,y:(-.5*p.y+.5)*height});}});
  const box={left:Math.min(...points.map(p=>p.x)),right:Math.max(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),bottom:Math.max(...points.map(p=>p.y))};box.cx=(box.left+box.right)/2;box.cy=(box.top+box.bottom)/2;const muzzle=weapon.muzzle.getWorldPosition(new THREE.Vector3()).project(camera);box.muzzle=[(muzzle.x*.5+.5)*width,(-muzzle.y*.5+.5)*height];box.armCount=weapon.group.userData.armCount||0;return box;
}
function diff(image,base,box){const py=`from PIL import Image,ImageChops,ImageStat\nimport json,sys\na=Image.open(sys.argv[1]).convert('RGB');b=Image.open(sys.argv[2]).convert('RGB');r=ImageChops.difference(a,b).crop(tuple(map(int,map(float,sys.argv[3:7]))));s=ImageStat.Stat(r);print(json.dumps({'meanDiff':round(sum(s.mean)/3,2),'peakDiff':max(v[1] for v in r.getextrema())}))`;const r=spawnSync('python3',['-c',py,image,base,String(box.left),String(box.top),String(box.right),String(box.bottom)],{encoding:'utf8'});if(r.status)throw new Error(r.stderr);return JSON.parse(r.stdout);}

for(const id of ids){const b=projection(WEAPONS[id]),cx=b.cx/width,cy=b.cy/height,overlaps=Object.fromEntries(buttonIds.map(x=>[x,+overlap(b,buttonRect(x)).toFixed(4)]));const pass=cx>=.55&&cx<=.70&&cy>=.72&&cy<=.82&&Object.values(overlaps).every(x=>x<.15)&&b.armCount>=1&&b.muzzle[0]>width*.5&&b.muzzle[0]<width*.58;report.weapons[id]={pass,cx:+cx.toFixed(4),cy:+cy.toFixed(4),muzzle:b.muzzle.map(x=>+x.toFixed(2)),armCount:b.armCount,overlaps};assert(pass,`${id} 投影、手臂或按钮避让不合格`);}

globalThis.localStorage={getItem(){return null;}};const bus=new EventBus(),camera=new THREE.PerspectiveCamera(),input={state:{move:{x:0,y:0}},consumeLook(){return{x:0,y:0}},consume(){return false}},map={collides(){return false}},stats={get(){return 1}},player=new PlayerController(camera,input,map,stats,bus),shake=new ScreenShake(camera,bus);bus.emit('weapon:shoot',{data:WEAPONS.shotgun});const initialKick=Math.hypot(player.crosshairKick.x,player.crosshairKick.y);player.update(.025,true);shake.update(.025);const firstPitch=camera.rotation.x,firstKick=Math.hypot(player.crosshairKick.x,player.crosshairKick.y),shakeDelta=shake.lastPosition.length();for(let i=1;i<8;i++){player.update(.025,true);shake.update(.025);}const recoveredKick=Math.hypot(player.crosshairKick.x,player.crosshairKick.y);for(let i=8;i<20;i++){player.update(.025,true);shake.update(.025);}const finalPitch=player.pitchOffset;
report.assertions.recoil={pass:firstPitch>.015&&firstPitch<.017&&finalPitch<.0004&&shakeDelta>0,firstPitch:+firstPitch.toFixed(6),oldExpectedFirstPitch:.008849,ratioToOld:+(firstPitch/.008849).toFixed(3),pitchAtHalfSecond:+finalPitch.toFixed(6),shakeDelta};assert(report.assertions.recoil.pass,'相机后坐力不合格');
report.assertions.crosshairKick={pass:initialKick<=5&&firstKick<initialKick&&recoveredKick<.05,initialMagnitude:+initialKick.toFixed(4),after25ms:+firstKick.toFixed(4),after200ms:+recoveredKick.toFixed(4),limitPx:5};assert(report.assertions.crosshairKick.pass,'准星微抖范围或恢复不合格');

const port=41729,server=spawn(process.platform==='win32'?'npm.cmd':'npm',['run','dev','--','--host','127.0.0.1','--port',String(port),'--strictPort'],{stdio:['ignore','pipe','pipe'],detached:process.platform!=='win32'});
try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Vite 启动超时')),15000),ready=d=>{if(String(d).includes('Local:')){clearTimeout(timer);resolve();}};server.stdout.on('data',ready);server.stderr.on('data',ready);});
  const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width,height},screen:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1}),page=await context.newPage();await page.goto(`http://127.0.0.1:${port}?verify=1`,{waitUntil:'networkidle'});
  await page.evaluate(weaponIds=>{window.__verifyGame.progression.data.unlockedWeapons=weaponIds;},ids);
  for(const id of ids){const data=WEAPONS[id],selection={pistol:'pistol',auto:'smg',shotgun:'shotgun'};selection[data.category]=id;await page.evaluate(selection=>{const g=window.__verifyGame;g.start({mapId:'base',weaponIds:selection});g.state='menu';g.waves.running=false;g.enemies.clear();g.player.pitch=0;g.player.pitchOffset=0;g.player.crosshairKick={x:0,y:0};g.engine.camera.rotation.set(0,g.player.yaw,0);},selection);await page.evaluate(id=>window.__verifyGame.switchWeapon(id,true),id);await page.waitForTimeout(80);const idle=new URL(`${id}-idle-812x375.png`,out).pathname,fire=new URL(`${id}-fire-812x375.png`,out).pathname,base=new URL(`${id}-baseline.png`,out).pathname;await page.screenshot({path:idle});await page.evaluate(()=>window.__verifyGame.weapon.group.visible=false);await page.screenshot({path:base});await page.evaluate(()=>window.__verifyGame.weapon.group.visible=true);const d=diff(idle,base,projection(data));report.weapons[id].pixelDiff=d;report.weapons[id].pass&&=d.meanDiff>2&&d.peakDiff>35;report.screenshots.push(`artifacts/step2-view/${id}-idle-812x375.png`);await page.evaluate(()=>{const g=window.__verifyGame;g.bus.emit('weapon:shoot',{data:g.weapon.data});g.weapon.fireTime=.05;g.weapon.update(0,false);g.player.update(.001,true);});await page.screenshot({path:fire});report.screenshots.push(`artifacts/step2-view/${id}-fire-812x375.png`);}
  await context.close();const desktop=await browser.newContext({viewport:{width:1280,height:720},screen:{width:1280,height:720},deviceScaleFactor:1}),desktopPage=await desktop.newPage();await desktopPage.goto(`http://127.0.0.1:${port}?verify=1`,{waitUntil:'networkidle'});await desktopPage.evaluate(()=>{const g=window.__verifyGame;g.start({mapId:'base'});g.state='menu';g.waves.running=false;g.enemies.clear();});await desktopPage.waitForTimeout(80);const overview=new URL('overview-1280x720.png',out).pathname;await desktopPage.screenshot({path:overview});report.screenshots.push('artifacts/step2-view/overview-1280x720.png');await desktop.close();await browser.close();
}finally{if(process.platform==='win32')server.kill('SIGTERM');else try{process.kill(-server.pid,'SIGTERM');}catch{}}
const expectedScreenshots=ids.length*2+1;report.assertions.screenshots={pass:report.screenshots.length===expectedScreenshots,count:report.screenshots.length,expected:expectedScreenshots};assert(report.assertions.screenshots.pass,'截图数量不合格');assert(Object.values(report.weapons).every(x=>x.pass),'武器截图差分不合格');fs.writeFileSync(new URL('verification.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
